### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by njraj** [Codepixl/codeOS2#2]
ld: cannot open output file out/disk/boot/codek32: No such file or directory
make: *** [codeos2] Error 1..what i do to fix this error

**Comment by byteduck** [comment]
You need to create the out directory (in the same folder as the makefile), and inside that the disk directory, and inside that the boot directory.

**Comment by njraj** [comment]
Thank you somuch for your kind response..I try to create directory like
what did you say..but now it shows error like"cp: cannot create
directory'/media/Aaron/codeOS2/':No such file or directory make: ***
(codeos2) Error 1..what to do to fix it.please help me

**Comment by njraj** [comment]
How can I fix this error..
Copy.sh/.
Cp: cannot create directory'/media/aaron/codeOS2':no such file or directory make:**
(codeOS2) error​ 1:I create the folder like what is shown in error..but that creation doesn't solve this error.. after creating the folder the error occur repeatedly.. how can I solve this problem.. please help me brother..
