### ISSUE TITLE
how to solve this...please help me

### ISSUE THREAD

**Issue by njraj** [Codepixl/codeOS2#3]
asm/startup.asm:27: warning: dword data exceeds bounds
ld -o out/disk/boot/codek32 *.o -T linker.ld -melf_i386 -Map kernel.map
rm *.o
./copy.sh
[sudo] password for njraj: 
sudo: C-x: command not found
make: *** [codeos2] Error 1

**Comment by piepert** [comment]
Remove the command "./copy.sh" from your Makefile.
You have to write the image on an USB-Drive.

**Comment by njraj** [comment]
Thank you so much for your kind response.. I will try your solution

**Comment by piepert** [comment]
```SRCS = $(wildcard src/kernel/*.c)
CFILES = $(patsubst %.c,%.o,$(SRCS))
INC = -Isrc/include/kernel
CFLAGS = -ffreestanding -std=gnu99 -Woverflow -m32 -fno-stack-protector
FLAGS =
CC = gcc
LD = ld

codeos2: $(CFILES)
	mv src/kernel/*.o .
	nasm asm/startup.asm -f elf -o startup.o
	ld -o bin/boot/codek.bin *.o -T linker.ld -melf_i386 -Map kernel.map
	grub-mkrescue bin --output=codeos2.iso
	rm *.o

run: codeos2
	qemu-system-x86_64 codeos2.iso

%.o: %.c
	$(CC) $(FLAGS) $(INC) $(CFLAGS) -c -o $@ $<
```
Remove your makefile and use this as yout makefile. This worked for me.
`make run` will create an iso (for CD/HardDrive) and runs it with qemu (you have to install it)

PS: Sorry, this won't work on a USB. My mistake.

**Comment by njraj** [comment]
Thankyou so much your help..I try this..it works..but when I boot it in
virtual box..and enter command boot..but it shows error"first load the
kernel"can you please tell me how to load the kernel

**Comment by piepert** [comment]
You have to create the directories bin, bin/boot and bin/boot/grub
Create a file in bin/boot/grub named "grub.cfg"
Write this into the file:

```
menuentry "CodeOS2" {
    multiboot2 /boot/codek.bin
    boot
}
```

This should work.

**Comment by njraj** [comment]
Thankyou somuch for your kind and immediate response.. I Will try
this..once again thank you so much for your help..thank you

**Comment by njraj** [comment]
Sir I try your solution.. It works..really thankyou somuch..for your kind
response.. If you don't mine..can you help two things..one is how I will
check and use codeos2 after boot it by using your solution.. Because after
boot it... I just see the word like" 32 bit file mode"
I just blank..please tell how to use the os...

Another thing is I would like to learn shell script..completely..can you
give suggestion for how to learn and implement practically..and give any
link for material to prepare...

Please please.. Help me..because I decided It is my carrier

**Comment by piepert** [comment]
So... Now we're at a point where I can't help you. I'm sorry, but I do not know more.

To learn shell scripting look at this website: https://www.shellscript.sh/philosophy.html
