### ISSUE TITLE
how to solve it

### ISSUE THREAD

**Issue by njraj** [Codepixl/codeOS2#4]
asm/startup.asm:27: warning: dword data exceeds bounds
ld -o out/disk/boot/codek32 *.o -T linker.ld -melf_i386 -Map kernel.map
rm *.o
./copy.sh
[sudo] password for njraj:
sudo: C-x: command not found
make: *** [codeos2] Error 1

**Comment by triploit** [comment]
Please... first learn Linux/Command Line and a bit about programming (in C) and then you can try to solve this by yourself.
